### ISSUE TITLE
[BUG] No Volume/Storage/Node after upgrading to 1.1.0

### ISSUE THREAD

**Issue by ralf-berger** [longhorn/longhorn#2118]
**Describe the bug**
After upgrading from 1.0.2 to 1.1.0 the UI doesn't show nodes or volumes anymore. The funny unlabled link icons in the bottom right switch between grey and red with the tooltip reading "undefined: error" or "undefinded: closed". All Longhorn-related workloads seem to be running as expected though.

**To Reproduce**
I upgraded Longhorn (installed as Rancher app) from 1.0.2 to 1.1.0.

**Expected behavior**
Longhorn UI should still show longhorny stuff.

**Log**
Seems like Longhorn UI logs only incoming web requests but no errors.

**Environment:**
 - Longhorn 1.1.0 installed as a Rancher app
 - Kubernetes v1.19.5-rancher1-1
 - Rancher standalone > 2.5.3 (rancher\rancher:master-head ref #ff16903)
 - Kubernetes config: Canal with network isolation, PSP support enabled
 - OS type and version: Ubuntu 20.04.1 LTS
 - CPU/Memory/Disk/Networking: mixed
 - Underlying Infrastructure: Hyper-V, bare metal

**Additional context**
The previous Longhorn release worked just fine.

**Comment by tomdoherty** [comment]
I also see this issue when upgrading from 1.0.1 to 1.1.0

**Comment by joshimoo** [comment]
The longhorn-ui uses websockets to communicate with the backend, the icons on the bottom right are the statuses of the websocket connections. Can you generate a support bundle manually, below are instructions to do this via curl please replace the longhorn-backend.xip.io with your own exposed service.

```
// requesting support bundle via post
curl -i -X POST -H 'Content-Type: application/json' -d '{ "issueURL": "https://github.com/longhorn/longhorn/issues/2118", "description": "2118" }' http://longhorn-backend.xip.io/v1/supportbundles

{"actions":{},"errorMessage":"","id":"longhorn-demo-work3","links":{"self":"http://longhorn-backend.xip.io/v1/supportbundles/longhorn-demo-work3"},"name":"longhorn-support-bundle_c9569901-9f06-44c6-978e-33294327d879_2020-12-18T13-49-05Z","nodeID":"longhorn-demo-work3","progressPercentage":0,"state":"InProgress","type":"supportbundle"}


// checking download status for the mentioned support bundle
curl -i -X GET http://longhorn-backend.xip.io/v1/supportbundles/longhorn-demo-work3/longhorn-support-bundle_c9569901-9f06-44c6-978e-33294327d879_2020-12-18T13-49-05Z

{"actions":{},"errorMessage":"","id":"longhorn-demo-work3","links":{"self":"http://longhorn-backend.xip.io/v1/supportbundles/longhorn-demo-work3"},"name":"longhorn-support-bundle_c9569901-9f06-44c6-978e-33294327d879_2020-12-18T13-49-05Z","nodeID":"longhorn-demo-work3","progressPercentage":100,"state":"ReadyForDownload","type":"supportbundle"}

// download support bundle mentioned above, once status is ReadyForDownload
curl -i -X GET http://longhorn-backend.xip.io/v1/supportbundles/longhorn-demo-work3/longhorn-support-bundle_c9569901-9f06-44c6-978e-33294327d879_2020-12-18T13-49-05Z/download --output /tmp/support-bundle.zip
```

**Comment by tomdoherty** [comment]
Provided on slack. Thanks @joshimoo

**Comment by timmy59100** [comment]
Same here.

**Comment by yasker** [comment]
Maybe related to https://github.com/longhorn/longhorn/issues/1777

**Comment by joshimoo** [comment]
The support bundle from @tomdoherty 
Shows that there is an ominous `/volume` prefix added when accessing the longhorn-ui via an ingress.

As a **workaround** you can access the longhorn-ui via port forwarding, we are investigating what's causing the ui not to work correctly.

**Comment by yasker** [comment]
It's the same as #1777.

If you’ve encountered this issue while using ingress in v1.1.0, please try closing all the tabs or restart your browser to clean the cache.

**Comment by ralf-berger** [comment]
> The longhorn-ui uses websockets to communicate with the backend […]

<img width="683" alt="Longhorn UI" src="https://user-images.githubusercontent.com/37848234/102640208-6ad2e400-415a-11eb-956a-0dd17c80c083.png">

* Longhorn UI Service type: Rancher-Proxy

**Comment by yasker** [comment]
@ralf-berger Can you check your `longhorn-manager` logs to see if there are any errors?

**Comment by Bobonium** [comment]
May be related, may be unrelated, but for me the 1.1.0 manager pods were restarting until I removed the `replica-replenishment-wait-interval` from the config file.

Log message in the manager was:
```
time="2020-12-18T16:56:35Z" level=fatal msg="Error starting manager: settings.longhorn.io \"replica-replenishment-wait-interval\" already exists"
```

After I removed the value from the config the upgrade without any problems

**Comment by ralf-berger** [comment]
> @ralf-berger Can you check your `longhorn-manager` logs to see if there are any errors?

No, nothing suspicious.

They tell me something about monitoring and that they're listening on port 9500, list all the rebuilds in progress over and over ("Skip rebuilding of replica because there is another rebuild in progress") and note an occasional GET request with response status 200. But literally not a single occurrence of the word "error" anywhere in there.

**Comment by yasker** [comment]
@ralf-berger Is it possible to generate a support bundle using https://github.com/longhorn/longhorn/issues/2118#issuecomment-748099002 ? Assume the service `longhorn-backend` is working. You can send it to `longhorn-support-bundle@rancher.com`

**Comment by shuo-wu** [comment]
> May be related, may be unrelated, but for me the 1.1.0 manager pods were restarting until I removed the `replica-replenishment-wait-interval` from the config file.
> 
> Log message in the manager was:
> 
> ```
> time="2020-12-18T16:56:35Z" level=fatal msg="Error starting manager: settings.longhorn.io \"replica-replenishment-wait-interval\" already exists"
> ```
> 
> After I removed the value from the config, the upgrade worked without any problems

This error is a transient error: When a new setting is introduced in the new version, all longhorn-manager pods will try to initialize the setting simultaneously then lead to this kind of conflict/error. 
But due to the retry and [check](https://github.com/longhorn/longhorn-manager/blob/87133daf86586398f74597c193dd63d702eb882c/datastore/longhorn.go#L48) mechanism, the manager pods can be running in the end. We will skip/ignore this creation conflict to avoid the unnecessary manager erroring out and retry.

**Comment by yasker** [comment]
Closing this issue due to lack of activity. Feel free to reopen the issue or file a new issue if you still have issues.

**Comment by mluds** [comment]
We still encounter this issue on Longhorn 1.1.0+. We get these errors from the browser. This is from a fresh private window:
```
robust-websocket.js:150 WebSocket connection to 'ws://bootstrap-green.dev.jpes.gov:8003/dashboard/v1/ws/1s/volumes' failed: 
M @ robust-websocket.js:150
robust-websocket.js:150 WebSocket connection to 'ws://bootstrap-green.dev.jpes.gov:8003/dashboard/v1/ws/1s/events' failed: 
M @ robust-websocket.js:150
robust-websocket.js:150 WebSocket connection to 'ws://bootstrap-green.dev.jpes.gov:8003/dashboard/v1/ws/1s/nodes' failed: 
M @ robust-websocket.js:150
robust-websocket.js:150 WebSocket connection to 'ws://bootstrap-green.dev.jpes.gov:8003/dashboard/v1/ws/1s/volumes' failed: 
M @ robust-websocket.js:150
robust-websocket.js:150 WebSocket connection to 'ws://bootstrap-green.dev.jpes.gov:8003/dashboard/v1/ws/1s/events' failed: 
M @ robust-websocket.js:150
robust-websocket.js:150
```
The result is that no information is shown on any of the dashboard pages.
We do not see this on 1.0.2. Both are brand new installs on a new cluster. Has anything changed related to websockets or endpoint URLs that may have caused this?

**Comment by PhanLe1010** [comment]
@mluds 
Did you try this https://github.com/longhorn/longhorn/issues/1777#issuecomment-691603283?

**Comment by mluds** [comment]
@PhanLe1010 
I feel silly now, but that fixed it. Thank you

We've been using kubectl port-forward, which still works, but I was using a bookmarked URL that was invalid.

**Comment by PhanLe1010** [comment]
Gotcha!
