### ISSUE TITLE
[IMPROVEMENT] update `azure-sdk-for-go` version to stable version

### ISSUE THREAD

**Issue by mantissahz** [longhorn/longhorn#8965]
## Describe the solution you'd like

According to https://github.com/longhorn/backupstore/pull/177, we need to update the `azure-sdk-for-go` to the stable version `v1.0.1`

```txt
azblob/azblob_service.go:31:25: undefined: azblob.ContainerClient
azblob/azblob_service.go:66:89: unknown field Transporter in struct literal of type "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob".ClientOptions
azblob/azblob_service.go:67:31: undefined: azblob.NewServiceClientFromConnectionString
azblob/azblob_service.go:87:25: undefined: azblob.ContainerListBlobHierarchySegmentOptions
azblob/azblob_service.go:108:59: undefined: azblob.GetBlobPropertiesResponse
azblob/azblob_service.go:138:108: unknown field MaxRetryRequests in struct literal of type blob.RetryReaderOptions
```

**Comment by chriscchien** [comment]
Hi @mantissahz,

I had [setup](https://confluence.suse.com/display/LON/Setup+Azurite+Backupsotre+For+Testing) an azurite backupsotre, it worked well in v1.7.0, but after I upgrade longhorn to `v1.8.0-dev-20240825` (or a fresh install), I can not create backup from UI and get see error in `backuptargets.longhorn.io` `default`

```yaml
Status:
  Available:  false
  Conditions:
    Last Probe Time:       
    Last Transition Time:  2024-08-26T08:06:58Z
    Message:               failed to list backup volumes in azblob://demo@core.windows.net/: error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.8.0-dev-20240825/longhorn [/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.8.0-dev-20240825/longhorn backup ls --volume-only azblob://demo@core.windows.net/], output GET http://10.43.80.140:10000/devstoreaccount1/demo
--------------------------------------------------------------------------------
RESPONSE 400: 400 The API version 2024-05-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 
ERROR CODE: InvalidHeaderValue
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidHeaderValue</Code>
  <Message>The API version 2024-05-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 
RequestId:47ad893d-c91f-4f98-af34-50662bc2753a
Time:2024-08-26T08:15:58.294Z</Message>
</Error>
--------------------------------------------------------------------------------

, stderr time="2024-08-26T08:15:58Z" level=error msg="GET http://10.43.80.140:10000/devstoreaccount1/demo\n--------------------------------------------------------------------------------\nRESPONSE 400: 400 The API version 2024-05-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter \"--skipApiVersionCheck\" or Visual Studio Code configuration \"Skip Api Version Check\" can skip this error. \nERROR CODE: InvalidHeaderValue\n--------------------------------------------------------------------------------\n<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidHeaderValue</Code>\n  <Message>The API version 2024-05-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter \"--skipApiVersionCheck\" or Visual Studio Code configuration \"Skip Api Version Check\" can skip this error. \nRequestId:47ad893d-c91f-4f98-af34-50662bc2753a\nTime:2024-08-26T08:15:58.294Z</Message>\n</Error>\n--------------------------------------------------------------------------------\n" func=main.ResponseLogAndError file="main.go:47"
: exit status 1
    Reason:        Unavailable
    Status:        True
    Type:          Unavailable
  Last Synced At:  2024-08-26T08:05:55Z
  Owner ID:        ip-172-31-83-204
Events:            <none>
```

[supportbundle_96f82278-240d-4609-804b-3d67a6534812_2024-08-26T08-14-05Z.zip](https://github.com/user-attachments/files/16746053/supportbundle_96f82278-240d-4609-804b-3d67a6534812_2024-08-26T08-14-05Z.zip)

**Comment by chriscchien** [comment]
Verified **pass** on longhorn `v1.8.0-dev-20240825` with test [steps](https://github.com/longhorn/longhorn/issues/8965#issuecomment-2299994026)

- Fresh install `v1.8.0-dev-20240825`
   - Backup v1 voume ,restore the volume to RWX/RWO volum success
   - Backup v2 voume ,restore the volume to RWX/RWO(V1) volum success
   - Backup v2 voume ,restore the volume to v2 volum success
   - Create system backup and restore success
- Have backup in `v1.7.0` then upgrade to `v1.8.0-dev-20240825`
   - Restore v1 volume to RWX/RWO volum success
   - Restore v2 voume to RWX/RWO(V1) volum success
   - Restore v2 voume to v2 volum success
