### ISSUE TITLE
[BUG] longhorn-manager v1.4.x cannot build after golang.org/x/tools update

### ISSUE THREAD

**Issue by ejweber** [longhorn/longhorn#7330]
## Describe the bug (🐛 if you encounter this issue)

Running `make build` from the root of the `longhorn-manager` `v1.4.x` branch since December 12 yields:

```
11.12 go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
11.52 go: downloading golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7
12.32 go: downloading golang.org/x/tools v0.16.1
13.21 go get: installing executables with 'go get' in module mode is deprecated.
13.21   Use 'go install pkg@version' instead.
13.21   For more information, see https://golang.org/doc/go-get-install-deprecation
13.21   or run 'go help get' or 'go help install'.
13.32 # golang.org/x/tools/internal/typeparams
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/common.go:45:8: undefined: ast.IndexListExpr
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/common.go:66:11: undefined: ast.IndexListExpr
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/common.go:160:32: undefined: types.Context
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/coretype.go:111:39: undefined: types.Term
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/normalize.go:63:30: undefined: types.TypeParam
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/normalize.go:63:51: undefined: types.Term
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/normalize.go:81:51: undefined: types.Term
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/normalize.go:91:26: undefined: types.Union
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/normalize.go:91:43: undefined: types.Term
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/normalize.go:95:41: undefined: types.Term
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/typeparams/common.go:66:11: too many errors
13.32 note: module requires Go 1.18
13.32 # golang.org/x/tools/go/ast/astutil
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/enclosing.go:323:23: n.Type.TypeParams undefined (type *ast.FuncType has no field or method TypeParams)
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/enclosing.go:378:8: undefined: ast.IndexListExpr
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/enclosing.go:589:8: undefined: ast.IndexListExpr
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/rewrite.go:253:8: undefined: ast.IndexListExpr
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/rewrite.go:294:18: n.TypeParams undefined (type *ast.FuncType has no field or method TypeParams)
13.32 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/rewrite.go:409:18: n.TypeParams undefined (type *ast.TypeSpec has no field or method TypeParams)
13.32 note: module requires Go 1.18
------
Dockerfile.dapper3504442777:19
--------------------
  18 |     
  19 | >>> RUN wget -O - https://storage.googleapis.com/golang/go1.17.10.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local && \
  20 | >>>     go get -u golang.org/x/lint/golint
  21 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c wget -O - https://storage.googleapis.com/golang/go1.17.10.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local &&     go get -u golang.org/x/lint/golint" did not complete successfully: exit code: 2
FATA[0018] exit status 1                                
make: *** [Makefile:11: build] Error 1
```

## To Reproduce

Run `make build` from the root of the `longhorn-manager` `v1.4.x` branch.

## Expected behavior

`longhorn-manager` builds.

## Additional context

Even though we set `go 1.21` in the `go.mod` file, we still build using `go 1.17`.

- https://github.com/longhorn/longhorn-manager/blob/c9e0a0ea4fdda4edf5c9061679322bfe02e8109c/go.mod#L3
- https://github.com/longhorn/longhorn-manager/blob/c9e0a0ea4fdda4edf5c9061679322bfe02e8109c/Dockerfile.dapper#L19-L20

I think this is intentional?

The error occurs when we try to install `golint` in the Dapper container. `golint` pins a version of the `golang.org/x/tools`, but our `go get -u golang.org/x/lint/golint` causes Go to attempt to use an updated version of all dependencies.

https://github.com/golang/lint/blob/6edffad5e6160f5949cdefc81710b2706fbcd4f6/go.mod#L5

Until `golang.org/x/tools` `v0.16.0`, this worked fine. For example, in this build from December 5, we `go get` retrieved `v0.16.0` without issue.

```
go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
go: downloading golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7
go: downloading golang.org/x/tools v0.16.0
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

https://drone-pr.longhorn.io/longhorn/longhorn-manager/6249/1/3

Somehow `golang.org/x/tools` `v0.16.1` finally broke compatibility.

To further confirm I swapped out `go get golang.org/x/tools/cmd/goimports` and `go get golang.org/x/tools/cmd/goimports@v0.16.0` for `go get -u golang.org/x/lint/golint` in the Dockerfile.dapper and got:

`go get golang.org/x/tools/cmd/goimports` fails.

```
11.34 go: downloading golang.org/x/tools v0.16.1
11.87 go: downloading golang.org/x/mod v0.14.0
13.00 go get: installing executables with 'go get' in module mode is deprecated.
13.00   Use 'go install pkg@version' instead.
13.00   For more information, see https://golang.org/doc/go-get-install-deprecation
13.00   or run 'go help get' or 'go help install'.
13.12 # golang.org/x/tools/go/ast/astutil
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/enclosing.go:323:23: n.Type.TypeParams undefined (type *ast.FuncType has no field or method TypeParams)
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/enclosing.go:378:8: undefined: ast.IndexListExpr
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/enclosing.go:589:8: undefined: ast.IndexListExpr
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/rewrite.go:253:8: undefined: ast.IndexListExpr
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/rewrite.go:294:18: n.TypeParams undefined (type *ast.FuncType has no field or method TypeParams)
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/go/ast/astutil/rewrite.go:409:18: n.TypeParams undefined (type *ast.TypeSpec has no field or method TypeParams)
13.12 note: module requires Go 1.18
13.12 # golang.org/x/tools/internal/event/keys
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/event/keys/util.go:14:6: missing function body
13.12 go/pkg/mod/golang.org/x/tools@v0.16.1/internal/event/keys/util.go:14:10: syntax error: unexpected [, expecting (
13.12 note: module requires Go 1.18
------
Dockerfile.dapper1753858196:19
--------------------
  18 |     
  19 | >>> RUN wget -O - https://storage.googleapis.com/golang/go1.17.10.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local && \
  20 | >>>     go get golang.org/x/tools/cmd/goimports
  21 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c wget -O - https://storage.googleapis.com/golang/go1.17.10.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local &&     go get golang.org/x/tools/cmd/goimports" did not complete successfully: exit code: 2
FATA[0018] exit status 1                                
make: *** [Makefile:11: build] Error 1
```

`go get golang.org/x/tools/cmd/goimports@v0.16.0` returns no error.

```
 => [5/5] WORKDIR /go/src/github.com/longhorn/longhorn-manager                                                                                                                                                                                                                                        0.0s
 => exporting to image             
```

@PhanLe1010 and I suggest just removing the `-u` flag from `go get -u golang.org/x/lint/golint` and I will open a PR to do that. I wanted to also open the bug report in case there are other concerns.

cc @c3y1huang since I think you have done the most around Go and dependency versions.

**Comment by ejweber** [comment]
Other branches are not affected because they are built with updated Go versions.

**Comment by PhanLe1010** [comment]
> @PhanLe1010 and I suggest just removing the -u flag from go get -u golang.org/x/lint/golint and I will open a PR to do that. I wanted to also open the bug report in case there are other concerns.

I am thinking if it make more sense to update golang version in dapper to `go 1.21` instead of removing the -u flag since we should use the same go version to build go module? So use something similar to master-head is doing:
```
RUN wget -O - https://storage.googleapis.com/golang/go1.21.5.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local && \
    go install golang.org/x/lint/golint@latest
```

**Comment by ejweber** [comment]
> I am thinking if it make more sense to update golang version in dapper to go 1.21 instead of removing the -u flag since we should use the same go version to build go module? So use something similar to master-head is doing:

Yes, I think it is a bit strange that we build with a lesser version than we declare in our `go.mod` file. However, we do that for both `v1.4.x` (`go 1.17`) and `v1.5.x` (`go 1.20`). Does anyone know why?

**Comment by PhanLe1010** [comment]
Maybe we forgot to update dapper when updating go.mod

**Comment by ejweber** [comment]
> Maybe we forgot to update dapper when updating go.mod?

That seems likely. It looks like the version in the Dapperfile is sometimes updated out-of-sync with the version in the `go.mod`. You would think an old version of Go would refuse to build a new version of a `go.mod`, but I guess not?

I'm inclined to agree that bumping the Go version used to build makes more sense, but I'm not sure if we are intentionally trying to avoid changing Go versions within a minor Longhorn version?

I'll give others a chance to weigh in before changing strategies.

**Comment by c3y1huang** [comment]
> > Maybe we forgot to update dapper when updating go.mod?
> 
> That seems likely. It looks like the version in the Dapperfile is sometimes updated out-of-sync with the version in the `go.mod`. You would think an old version of Go would refuse to build a new version of a `go.mod`, but I guess not?
> 
> I'm inclined to agree that bumping the Go version used to build makes more sense, but I'm not sure if we are intentionally trying to avoid changing Go versions within a minor Longhorn version?
> 
> I'll give others a chance to weigh in before changing strategies.

Sorry, I forgot to update the Dapper file causing the Dapper Go version out of sync with the go.mod file. This was unintended. @ejweber since you are handling this now, could you have another PR to update Dapper and backport to v1.5.x and v1.4.x ?

**Comment by ejweber** [comment]
Sorry, I forgot to update the Dapper file causing the Dapper Go version out of sync with the go.mod file. This was unintended. @ejweber since you are handling this now, could you have another PR to update Dapper and backport to v1.5.x and v1.4.x ?

Will do. Thanks for the feedback @c3y1huang.

**Comment by ejweber** [comment]
Will be fixed as a consequence of https://github.com/longhorn/longhorn/issues/7341.

**Comment by innobead** [comment]
> > > Maybe we forgot to update dapper when updating go.mod?
> > 
> > 
> > That seems likely. It looks like the version in the Dapperfile is sometimes updated out-of-sync with the version in the `go.mod`. You would think an old version of Go would refuse to build a new version of a `go.mod`, but I guess not?
> > I'm inclined to agree that bumping the Go version used to build makes more sense, but I'm not sure if we are intentionally trying to avoid changing Go versions within a minor Longhorn version?
> > I'll give others a chance to weigh in before changing strategies.
> 
> Sorry, I forgot to update the Dapper file causing the Dapper Go version out of sync with the go.mod file. This was unintended. @ejweber since you are handling this now, could you have another PR to update Dapper and backport to v1.5.x and v1.4.x ?
> 
> Ref: #7001, #7151

But why the PR check was passed w/o issues?

**Comment by innobead** [comment]
> > Maybe we forgot to update dapper when updating go.mod?
> 
> That seems likely. It looks like the version in the Dapperfile is sometimes updated out-of-sync with the version in the `go.mod`. You would think an old version of Go would refuse to build a new version of a `go.mod`, but I guess not?
> 

It should be, but it's not enforced, so this was why we did not catch it earlier. 
> The go directive sets the minimum version of Go required to use this module. Before Go 1.21, the directive was advisory only; now it is a mandatory requirement: Go toolchains refuse to use modules declaring newer Go versions.

**Comment by innobead** [comment]
It's not caused by the recent update of the min go version in go.mod, even though we **SHOULD** fix the dapper env to use the same version, this is 100% correct and was missed due to the previous PR check passed..

The recent release from https://cs.opensource.google/go/x/tools/+/refs/tags/v0.16.1:go.mod;l=3 caused it. Because golang.org/x/lint/golint depends on it and it doesn't use any specific tag referring to a version of the tools module, then a pesudo version just gets adopted, which means it will be updated when using `go get -u`.

The correct way is to install a specific version of `golint` instead of `golint@latest`. However, we should use https://github.com/golangci/golangci-lint instead of golint, because it is inactive and deprecated now.

**Comment by innobead** [comment]
To make the build move forward, the short-term solution is to align the Go version with the version in go.mod, then the deprecated golint can still be used.
